# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-22 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentstructuremodel',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
