# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0004_auto_20160722_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantmodel',
            name='buyin_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restservice.BuyinStructureModel'),
        ),
    ]
