# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-22 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0005_participantmodel_buyin_structure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParticipantModel',
            new_name='PlayerModel',
        ),
    ]
