# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0006_auto_20160722_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='eliminated',
            field=models.BooleanField(default=False),
        ),
    ]
