# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0007_playermodel_eliminated'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
