# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0008_lastupdatemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lastupdatemodel',
            options={'get_latest_by': 'last_update'},
        ),
    ]
