# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0010_delete_lastupdatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmodel',
            name='is_break',
            field=models.BooleanField(default=False),
        ),
    ]
