# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-26 20:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0011_roundmodel_is_break'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundOrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('round_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restservice.RoundModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='tournamentstructuremodel',
            name='rounds',
        ),
        migrations.AddField(
            model_name='roundordermodel',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restservice.TournamentStructureModel'),
        ),
        migrations.AddField(
            model_name='tournamentstructuremodel',
            name='round_list',
            field=models.ManyToManyField(through='restservice.RoundOrderModel', to='restservice.RoundModel'),
        ),
    ]
