# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0012_auto_20160726_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roundordermodel',
            options={'ordering': ('number',)},
        ),
    ]
