# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0013_auto_20160728_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roundordermodel',
            name='round_model',
        ),
        migrations.RemoveField(
            model_name='roundordermodel',
            name='structure',
        ),
        migrations.RemoveField(
            model_name='tournamentstructuremodel',
            name='round_list',
        ),
        migrations.AddField(
            model_name='roundmodel',
            name='tournament',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restservice.TournamentStructureModel'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RoundOrderModel',
        ),
    ]
