# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-28 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0014_auto_20160728_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='roundmodel',
            name='number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
