# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-29 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restservice', '0018_adminmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminmodel',
            name='device_id',
            field=models.UUIDField(null=True),
        ),
    ]
